CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (100),
IDADE INT,
SERIE VARCHAR(100)
);

INSERT INTO ALUNOS (ID,NOME, IDADE, SERIE)
VALUES
(1,"PEDRO", 15, "PRIMEIRO ANO"),
(2,"PAULO", 15, "SEGUNDO ANO"),
(3,"JOÃO", 17,"TERCEIRO ANO"),
(4,"MATIAS", 16, "TERCEIRO ANO"),
(5,"YASMINE", 15,"SEGUNDO ANO");

SELECT * FROM ALUNOS;
SELECT NOME, IDADE FROM ALUNOS;
SELECT * FROM ALUNOS WHERE SERIE = "SEGUNDO ANO";
UPDATE ALUNOS
SET IDADE = 25
WHERE ID = 4;
DELETE FROM ALUNOS WHERE ID = 2;
