CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    IDADE INT,
    CIDADE VARCHAR(100),
    SERIE VARCHAR(50)
);


INSERT INTO ALUNOS (ID,NOME, IDADE, SERIE)
VALUES
(1,"PEDRO", 15, "PRIMEIRO ANO"),
(2,"PAULO", 15, "SEGUNDO ANO"),
(3,"JOÃO", 17,"TERCEIRO ANO"),
(4,"MATIAS", 16, "TERCEIRO ANO"),
(5,"YASMINE", 15,"SEGUNDO ANO");

SELECT * FROM ALUNOS;
SELECT  NOME, IDADE FROM ALUNOS;
SELECT * FROM ALUNOS WHERE SERIE = 'SEGUNDO ANO';
UPDATE ALUNOS SET IDADE = 25 WHERE ID = 4;
DELETE FROM ALUNOS WHERE  ID = 2;

CREATE TABLE CURSOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_CURSO VARCHAR(50),
CARGA_HORARIA INT,
SERIE VARCHAR(50)
);

CREATE TABLE MATRICULAS(
ID INT AUTO_INCREMENT PRIMARY KEY,
ALUNO_ID INT,
CURSO_ID INT,
DATA_MATRICULA DATE,
FOREIGN KEY (ALUNO_ID) REFERENCES ALUNOS (ID),
FOREIGN KEY (CURSO_ID) REFERENCES CURSOS (ID)
);

INSERT INTO ALUNOS (NOME, IDADE, CIDADE, SERIE)
VALUES 
('Maria Silva', 20, 'São Paulo'), 
('João Santos', 22, 'Rio de Janeiro'), 
('Ana Souza', 19, 'Belo Horizonte'), 
('Carlos Pereira', 25, 'Curitiba'); 


INSERT INTO Cursos (nome_curso, carga_horaria) 
VALUES  
('Banco de Dados', 40), 
('Lógica de Programação', 60), 
('Desenvolvimento Web', 80); 

INSERT INTO Matriculas (aluno_id, curso_id, data_matricula) 
VALUES  
(1, 1, '2024-02-15'), 
(2, 2, '2024-03-10'), 
(3, 1, '2024-04-05'), 
(4, 3, '2024-05-20'); 


SELECT * FROM ALUNOS;

SELECT NOME, IDADE FROM ALUNOS WHERE IDADE > 20;
SELECT NOME, CIDADE WHERE CIDADE = "SÃO PAULO";
SELECT NOME_CURSO, CARGA_HORARIA FROM CURSOS WHERE CARGA_HORARIA<70;




